from . import UINode, Nodes
from GUI.nodeTraits import TraitInt

class PiCamUINode( UINode ):
    def __init__( self ):
        super( PiCamUINode, self ).__init__( "PiCamNode" )
        self.type_info = Nodes.TYPE_CAMERA_MC_PI

        # Maybe these should be in a JSON file, rather than hardcoded?
        self.traits = {
            "fps"        : TraitInt( "fps", 60, 0, 60,
                                        value=None,
                                        units="Frames per Second",
                                        units_short="fps",
                                        human_name="Frame Rate",
                                        desc="Camera Frame Rate",
                                        mode="rwa" ),

            "strobe"     : TraitInt( "strobe", 20, 0, 70,
                                        value=None,
                                        units="Watts",
                                        units_short="W",
                                        human_name="Strobe Power",
                                        desc="Strobe LED Power",
                                        mode="rw" ),

            "shutter"    : TraitInt( "shutter", 8, 2, 250,
                                        value=None,
                                        units="100's of uSecs",
                                        units_short="100uS",
                                        human_name="Exposure Time",
                                        desc="Shutter Period for camera",
                                        mode="rw" ),

            "mtu"        : TraitInt( "mtu", 0, 0, 8,
                                         value=None,
                                         units="kilobytes above 1500",
                                       units_short="kb",
                                         human_name="Packet Size",
                                         desc="Additional Packet Size (Jumbo Frames)",
                                         mode="rwa" ),

            "iscale"     : TraitInt( "iscale", 1, 1, 128,
                                         value=None,
                                         units="Powers of 2",
                                       units_short="/2^X",
                                         human_name="Image decimation",
                                         desc="Scale down image by powers of 2",
                                         mode="rwa" ),

            "idelay"     : TraitInt( "idelay", 15, 3, 255,
                                         value=None,
                                         units="Arbitrary Units",
                                       units_short="?",
                                         human_name="Image Delay",
                                         desc="Deley between sending fragmented images",
                                         mode="rwa" ),

            "threshold"  : TraitInt( "threshold", 128, 0, 255,
                                         value=None,
                                         units="8-Bit Grey Level",
                                       units_short="b",
                                         human_name="Threshold",
                                         desc="Image Thresholding",
                                         mode="rw" ),

            "numdets"    : TraitInt( "numdets", 13, 0, 80,
                                         value=None,
                                         units="10s of Centroids",
                                       units_short="100x",
                                         human_name="Centroids per Packet",
                                         desc="Limit number of Centroids in a packet",
                                         mode="rwa" ),

            "arpdelay"   : TraitInt( "arpdelay", 15, 0, 255,
                                         value=None,
                                         units="Arbitrary Units",
                                       units_short="?",
                                         human_name="Gratuitous ARP Delay",
                                         desc="ARP Interval",
                                         mode="rwa" ),

            # 3-axis IMU
            # ToDo: Need to represent bitfields, and probably other types
            "impactflags": TraitInt( "impactflags", 60, 0, 60,#lambda x: '{:08b}'.format(x)
                                         value=None,
                                         units="",
                                        units_short="Flag",
                                         human_name="Impact Warning Flags",
                                         desc="",
                                         mode="rw" ),

            "impactlimit": TraitInt( "impactlimit", 150, 0, 255,
                                         value=None,
                                         units="1/10th RMS deviation",
                                         human_name="Impact Threashold",
                                         desc="RMS Impact Deviation Threashold ",
                                         mode="rwa" ),


            # ToDo: These need a NodeTrait3D type
            "impactrefx" : TraitInt( "impactrefx", 0, -1023, 1023,
                                         value=None,
                                         units="Arbitrary Units",
                                         human_name="Impact Reference X",
                                         desc="Calibrated IMU Pos X",
                                         mode="rwa" ),

            "impactrefy" : TraitInt( "impactrefy", 0, -1023, 1023,
                                         value=None,
                                         units="Arbitrary Units",
                                         human_name="Impact Reference Y",
                                         desc="Calibrated IMU Pos Y",
                                         mode="rwa" ),

            "impactrefz" : TraitInt( "impactrefz", 0, -1023, 1023,
                                         value=None,
                                         units="Arbitrary Units",
                                         human_name="Impact Reference Z",
                                         desc="Calibrated IMU Pos Z",
                                         mode="rwa" ),

            "impactvalx" : TraitInt( "impactvalx", 0, -1023, 1023,
                                         value=None,
                                         units="Arbitrary Units",
                                         human_name="Impact Value X",
                                         desc="Measured IMU Pos X",
                                         mode="ra" ),

            "impactvaly" : TraitInt( "impactvaly", 0, -1023, 1023,
                                         value=None,
                                         units="Arbitrary Units",
                                         human_name="Impact Value Y",
                                         desc="Measured IMU Pos Y",
                                         mode="ra" ),

            "impactvalz" : TraitInt( "impactvalz", 0, -1023, 1023,
                                         value=None,
                                         units="Arbitrary Units",
                                         human_name="Impact Value Z",
                                         desc="Measured IMU Pos Z",
                                         mode="ra" ),
        }
        self.trait_order = [ "fps", "strobe", "shutter", "mtu", "iscale", "idelay",
                             "threshold", "numdets", "arpdelay", "impactflags",
                             "impactlimit", "impactrefx", "impactrefy", "impactrefz",
                             "impactvalx", "impactvaly", "impactvalz" ]

        # No idea how to deal with these ATM
        self.special_traits = {
            # Masking Zones (auto Generated)
            "maskzone01x": TraitInt( "maskzone01x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 01 LEFT",
                                         desc="Mask 01 position Left",
                                         mode="rwx" ),

            "maskzone01y": TraitInt( "maskzone01y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 01 TOP",
                                         desc="Mask 01 position Top",
                                         mode="rwx" ),

            "maskzone01m": TraitInt( "maskzone01m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 01 RIGHT",
                                         desc="Mask 01 position Right",
                                         mode="rwx" ),

            "maskzone01n": TraitInt( "maskzone01n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 01 BOTTOM",
                                         desc="Mask 01 position Bottom",
                                         mode="rwx" ),

            "maskzone02x": TraitInt( "maskzone02x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 02 LEFT",
                                         desc="Mask 02 position Left",
                                         mode="rwx" ),

            "maskzone02y": TraitInt( "maskzone02y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 02 TOP",
                                         desc="Mask 02 position Top",
                                         mode="rwx" ),

            "maskzone02m": TraitInt( "maskzone02m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 02 RIGHT",
                                         desc="Mask 02 position Right",
                                         mode="rwx" ),

            "maskzone02n": TraitInt( "maskzone02n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 02 BOTTOM",
                                         desc="Mask 02 position Bottom",
                                         mode="rwx" ),

            "maskzone03x": TraitInt( "maskzone03x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 03 LEFT",
                                         desc="Mask 03 position Left",
                                         mode="rwx" ),

            "maskzone03y": TraitInt( "maskzone03y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 03 TOP",
                                         desc="Mask 03 position Top",
                                         mode="rwx" ),

            "maskzone03m": TraitInt( "maskzone03m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 03 RIGHT",
                                         desc="Mask 03 position Right",
                                         mode="rwx" ),

            "maskzone03n": TraitInt( "maskzone03n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 03 BOTTOM",
                                         desc="Mask 03 position Bottom",
                                         mode="rwx" ),

            "maskzone04x": TraitInt( "maskzone04x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 04 LEFT",
                                         desc="Mask 04 position Left",
                                         mode="rwx" ),

            "maskzone04y": TraitInt( "maskzone04y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 04 TOP",
                                         desc="Mask 04 position Top",
                                         mode="rwx" ),

            "maskzone04m": TraitInt( "maskzone04m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 04 RIGHT",
                                         desc="Mask 04 position Right",
                                         mode="rwx" ),

            "maskzone04n": TraitInt( "maskzone04n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 04 BOTTOM",
                                         desc="Mask 04 position Bottom",
                                         mode="rwx" ),

            "maskzone05x": TraitInt( "maskzone05x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 05 LEFT",
                                         desc="Mask 05 position Left",
                                         mode="rwx" ),

            "maskzone05y": TraitInt( "maskzone05y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 05 TOP",
                                         desc="Mask 05 position Top",
                                         mode="rwx" ),

            "maskzone05m": TraitInt( "maskzone05m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 05 RIGHT",
                                         desc="Mask 05 position Right",
                                         mode="rwx" ),

            "maskzone05n": TraitInt( "maskzone05n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 05 BOTTOM",
                                         desc="Mask 05 position Bottom",
                                         mode="rwx" ),

            "maskzone06x": TraitInt( "maskzone06x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 06 LEFT",
                                         desc="Mask 06 position Left",
                                         mode="rwx" ),

            "maskzone06y": TraitInt( "maskzone06y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 06 TOP",
                                         desc="Mask 06 position Top",
                                         mode="rwx" ),

            "maskzone06m": TraitInt( "maskzone06m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 06 RIGHT",
                                         desc="Mask 06 position Right",
                                         mode="rwx" ),

            "maskzone06n": TraitInt( "maskzone06n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 06 BOTTOM",
                                         desc="Mask 06 position Bottom",
                                         mode="rwx" ),

            "maskzone07x": TraitInt( "maskzone07x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 07 LEFT",
                                         desc="Mask 07 position Left",
                                         mode="rwx" ),

            "maskzone07y": TraitInt( "maskzone07y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 07 TOP",
                                         desc="Mask 07 position Top",
                                         mode="rwx" ),

            "maskzone07m": TraitInt( "maskzone07m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 07 RIGHT",
                                         desc="Mask 07 position Right",
                                         mode="rwx" ),

            "maskzone07n": TraitInt( "maskzone07n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 07 BOTTOM",
                                         desc="Mask 07 position Bottom",
                                         mode="rwx" ),

            "maskzone08x": TraitInt( "maskzone08x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 08 LEFT",
                                         desc="Mask 08 position Left",
                                         mode="rwx" ),

            "maskzone08y": TraitInt( "maskzone08y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 08 TOP",
                                         desc="Mask 08 position Top",
                                         mode="rwx" ),

            "maskzone08m": TraitInt( "maskzone08m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 08 RIGHT",
                                         desc="Mask 08 position Right",
                                         mode="rwx" ),

            "maskzone08n": TraitInt( "maskzone08n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 08 BOTTOM",
                                         desc="Mask 08 position Bottom",
                                         mode="rwx" ),

            "maskzone09x": TraitInt( "maskzone09x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 09 LEFT",
                                         desc="Mask 09 position Left",
                                         mode="rwx" ),

            "maskzone09y": TraitInt( "maskzone09y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 09 TOP",
                                         desc="Mask 09 position Top",
                                         mode="rwx" ),

            "maskzone09m": TraitInt( "maskzone09m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 09 RIGHT",
                                         desc="Mask 09 position Right",
                                         mode="rwx" ),

            "maskzone09n": TraitInt( "maskzone09n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 09 BOTTOM",
                                         desc="Mask 09 position Bottom",
                                         mode="rwx" ),

            "maskzone10x": TraitInt( "maskzone10x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 10 LEFT",
                                         desc="Mask 10 position Left",
                                         mode="rwx" ),

            "maskzone10y": TraitInt( "maskzone10y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 10 TOP",
                                         desc="Mask 10 position Top",
                                         mode="rwx" ),

            "maskzone10m": TraitInt( "maskzone10m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 10 RIGHT",
                                         desc="Mask 10 position Right",
                                         mode="rwx" ),

            "maskzone10n": TraitInt( "maskzone10n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 10 BOTTOM",
                                         desc="Mask 10 position Bottom",
                                         mode="rwx" ),

            "maskzone11x": TraitInt( "maskzone11x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 11 LEFT",
                                         desc="Mask 11 position Left",
                                         mode="rwx" ),

            "maskzone11y": TraitInt( "maskzone11y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 11 TOP",
                                         desc="Mask 11 position Top",
                                         mode="rwx" ),

            "maskzone11m": TraitInt( "maskzone11m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 11 RIGHT",
                                         desc="Mask 11 position Right",
                                         mode="rwx" ),

            "maskzone11n": TraitInt( "maskzone11n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 11 BOTTOM",
                                         desc="Mask 11 position Bottom",
                                         mode="rwx" ),

            "maskzone12x": TraitInt( "maskzone12x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 12 LEFT",
                                         desc="Mask 12 position Left",
                                         mode="rwx" ),

            "maskzone12y": TraitInt( "maskzone12y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 12 TOP",
                                         desc="Mask 12 position Top",
                                         mode="rwx" ),

            "maskzone12m": TraitInt( "maskzone12m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 12 RIGHT",
                                         desc="Mask 12 position Right",
                                         mode="rwx" ),

            "maskzone12n": TraitInt( "maskzone12n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 12 BOTTOM",
                                         desc="Mask 12 position Bottom",
                                         mode="rwx" ),

            "maskzone13x": TraitInt( "maskzone13x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 13 LEFT",
                                         desc="Mask 13 position Left",
                                         mode="rwx" ),

            "maskzone13y": TraitInt( "maskzone13y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 13 TOP",
                                         desc="Mask 13 position Top",
                                         mode="rwx" ),

            "maskzone13m": TraitInt( "maskzone13m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 13 RIGHT",
                                         desc="Mask 13 position Right",
                                         mode="rwx" ),

            "maskzone13n": TraitInt( "maskzone13n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 13 BOTTOM",
                                         desc="Mask 13 position Bottom",
                                         mode="rwx" ),

            "maskzone14x": TraitInt( "maskzone14x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 14 LEFT",
                                         desc="Mask 14 position Left",
                                         mode="rwx" ),

            "maskzone14y": TraitInt( "maskzone14y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 14 TOP",
                                         desc="Mask 14 position Top",
                                         mode="rwx" ),

            "maskzone14m": TraitInt( "maskzone14m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 14 RIGHT",
                                         desc="Mask 14 position Right",
                                         mode="rwx" ),

            "maskzone14n": TraitInt( "maskzone14n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 14 BOTTOM",
                                         desc="Mask 14 position Bottom",
                                         mode="rwx" ),

            "maskzone15x": TraitInt( "maskzone15x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 15 LEFT",
                                         desc="Mask 15 position Left",
                                         mode="rwx" ),

            "maskzone15y": TraitInt( "maskzone15y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 15 TOP",
                                         desc="Mask 15 position Top",
                                         mode="rwx" ),

            "maskzone15m": TraitInt( "maskzone15m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 15 RIGHT",
                                         desc="Mask 15 position Right",
                                         mode="rwx" ),

            "maskzone15n": TraitInt( "maskzone15n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 15 BOTTOM",
                                         desc="Mask 15 position Bottom",
                                         mode="rwx" ),

            "maskzone16x": TraitInt( "maskzone16x", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 16 LEFT",
                                         desc="Mask 16 position Left",
                                         mode="rwx" ),

            "maskzone16y": TraitInt( "maskzone16y", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 16 TOP",
                                         desc="Mask 16 position Top",
                                         mode="rwx" ),

            "maskzone16m": TraitInt( "maskzone16m", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 16 RIGHT",
                                         desc="Mask 16 position Right",
                                         mode="rwx" ),

            "maskzone16n": TraitInt( "maskzone16n", 0, 0, 4096,
                                         value=None,
                                         units="Pixels",
                                         human_name="Mask Zone 16 BOTTOM",
                                         desc="Mask 16 position Bottom",
                                         mode="rwx" ),

        }

        # OK
        self._survey()